In [1]:
from astropy.io import fits
import pandas as pd
import os



with fits.open('/kaggle/input/datasets/maanav0114/harps-n-dataset/ADP.2023-12-04T15_16_53.464.fits') as data:
    harps_df = pd.DataFrame(data[1].data)

# Fix the big-endian to little-endian compiler issue
harps_df.to_csv('/kaggle/working/temp.csv', index = False)
del harps_df
harps_df = pd.DataFrame(pd.read_csv('/kaggle/working/temp.csv'))
os.remove('/kaggle/working/temp.csv')

harps_df.describe()

/usr/local/lib/python3.12/dist-packages/pandas/core/nanops.py:1016: RuntimeWarning: overflow encountered in square
  sqr = _ensure_numeric((avg - values) ** 2)

,tel_targ_alpha,tel_targ_delta,mjd_obs,exptime,ins_det1_tmmean,drs_bjd,drs_version_number,drs_snr,drs_berv,drs_ccf_rvc,...,pmdec_simbad,pmra_err_simbad,pmdec_err_simbad,pm_err_pa_simbad,Bmag_simbad,Vmag_simbad,Jmag_simbad,Hmag_simbad,Kmag_simbad,angDist_simbad
count,289843.000000,289843.000000,289843.000000,289843.000000,289843.000000,2.898430e+05,289842.000000,2.898430e+05,289843.000000,282294.000000,...,286314.000000,286160.000000,286160.000000,289843.000000,281625.000000,280194.000000,284186.000000,284110.000000,284175.000000,286766.000000
mean,177.214614,-32.856650,55673.352683,383.517457,0.472764,2.455674e+06,3.565870,-2.210453e+02,-0.812685,1255.906524,...,-29.278840,1.627111,1.514380,-339.983187,6.655004,5.954157,4.696480,4.346067,4.251171,0.884084
std,103.480554,26.652877,1720.035753,502.501236,0.086737,1.720036e+03,0.124186,1.994431e+05,14.992151,11342.374647,...,788.310609,5.155810,4.912895,3679.010556,3.255201,3.136321,2.886256,2.894555,2.876160,3.152134
min,0.000000,-88.818294,52901.354457,0.000000,-1.200000,2.452902e+06,3.500000,-1.073742e+08,-30.545979,-100008.611844,...,-5708.614000,0.007000,0.008000,-32768.000000,0.300000,0.010000,-3.000000,-3.730000,-4.050000,0.000000
25%,86.821208,-59.302156,54290.341733,40.001500,0.480000,2.454291e+06,3.500000,6.380000e+01,-12.327566,-19.753620,...,-214.278000,0.022000,0.020000,90.000000,4.220000,3.710000,2.840000,2.349000,2.237000,0.008873
50%,198.013271,-35.843611,55438.006770,135.505800,0.500000,2.455439e+06,3.500000,1.389500e+02,-0.670219,-1.018182,...,-14.942000,0.072000,0.065000,90.000000,6.150000,5.580000,4.750000,4.400000,4.298000,0.021803
75%,259.859883,-9.458250,56848.158706,600.001000,0.510000,2.456849e+06,3.500000,2.208500e+02,10.423184,19.441109,...,188.554000,0.161000,0.123000,90.000000,8.850000,8.130000,6.734000,6.397000,6.297000,0.181891
max,359.979458,29.830172,60094.086925,7199.995900,6.860000,2.460095e+06,3.800000,6.912500e+02,30.535827,182136.783699,...,10362.394000,33.000000,42.000000,32767.000000,20.290000,19.390000,17.610000,17.900000,17.970000,29.930780

In [2]:
hires_df = pd.DataFrame(pd.read_csv('/kaggle/input/datasets/maanav0114/harps-n-dataset/preprocessed_HIRES_data.csv'))

hires_df.describe()

            drs_bjd   drs_ccf_rvc     drs_dvrms
count  7.506200e+04  75062.000000  75062.000000
mean   2.454893e+06     -9.499061      1.880604
std    1.989164e+03    940.329217      3.903587
min    2.450276e+06 -46649.640000      0.010000
25%    2.453577e+06     -4.810000      1.200000
50%    2.455081e+06      0.000000      1.400000
75%    2.456134e+06      4.510000      1.720000
max    2.458919e+06  41546.190000    373.170000

In [3]:
exo_catalog = pd.DataFrame(pd.read_csv('/kaggle/input/datasets/maanav0114/harps-n-dataset/catalog_of_exoplanets3.csv'))
exo_catalog.describe()

,mass,mass_error_min,mass_error_max,mass_sini,mass_sini_error_min,mass_sini_error_max,radius,radius_error_min,radius_error_max,orbital_period,...,star_mass_error_max,star_radius,star_radius_error_min,star_radius_error_max,star_age,star_age_error_min,star_age_error_max,star_teff,star_teff_error_min,star_teff_error_max
count,4.498000e+03,4741.000000,4750.000,1771.000000,1426.000000,1426.000000,7278.000000,6454.000000,6454.000000,8.950000e+03,...,7.507000e+03,8595.000000,7499.000000,7499.000000,4480.000000,3909.000000,3909.000000,8777.000000,8220.000000,8220.000000
mean,1.442737e+01,4.752917,inf,6.871274,0.998356,4.174371,2.653069,0.537156,1.087954,2.950029e+04,...,1.179026e+03,1.627921,0.157105,0.233238,4.260824,0.491198,2.739989,5569.601847,142.707670,140.236300
std,2.006302e+01,24.786033,NaN,20.451316,12.928960,73.773993,49.520753,13.988412,25.070070,2.186592e+06,...,1.021433e+05,6.493147,0.665984,1.412749,4.917804,2.707530,9.443888,3187.426913,1012.478695,1010.215926
min,3.000000e-12,0.000000,-17.800,0.000190,0.000000,0.000000,0.000000,0.000000,0.000000,1.180600e-02,...,-1.300000e-01,0.000014,-0.180000,-0.180000,0.000020,-7.410000,-2.600000,909.000000,-98.231100,0.000000
25%,1.654250e-01,0.012900,0.012,0.067666,0.007000,0.007232,0.139000,0.011000,0.014300,4.327100e+00,...,4.000000e-02,0.770000,0.030000,0.030000,2.000000,-1.400000,0.740000,4905.000000,70.000000,70.000000
50%,2.800000e+00,0.130000,0.130,1.210000,0.060000,0.064000,0.226000,0.020880,0.033900,1.207244e+01,...,7.000000e-02,0.963000,0.060000,0.069000,3.980000,0.440000,2.000000,5573.000000,111.950000,109.285000
75%,2.404500e+01,1.900000,2.000,6.000000,0.300000,0.310000,0.766927,0.050000,0.070000,6.044224e+01,...,1.330000e-01,1.270000,0.117000,0.260000,5.400000,2.000000,3.970000,5963.000000,151.109000,155.000000
max,7.827000e+01,596.860537,inf,690.000000,480.000000,2100.000000,2603.000000,705.060000,1355.160000,2.060000e+08,...,8.850000e+06,335.000000,28.970000,104.530000,259.400000,86.000000,500.000000,200000.000000,88113.000000,88113.000000

In [4]:
def get_star_names(idx):
    name_list = []

    name_strs = (f"{exo_catalog.iloc[idx]['star_name']}, {exo_catalog.iloc[idx]['star_alternate_names']}").split(",")
    for name in name_strs:
        name = name.strip()
        name_list.append(name)

    return name_list

In [6]:
# for hires_name in list(set(list(hires_df['main_id_simbad']))):
#     for harps_name in list(set(list(harps_df['main_id_simbad']))):
#         if hires_name in harps_name or harps_name in hires_name:
#             print(hires_name)
#             print(harps_name)
#             break

In [11]:
harps_stars = []
for name in list(set(list(harps_df['main_id_simbad']))):
    name = name.split(" ")
    name = "".join(name)
    name = name.lower()

    harps_stars.append(name)

harps_stars[:10]

['tyc306-206-1',
 '*omitau',
 'hd14747',
 'v*yypic',
 'hd211583',
 'v*tsex',
 'ngc67051101',
 'hd70509',
 'hd213885',
 'cd-2616866a']

In [ ]:
observations = harps_df
cols_to_keep = ['main_id_simbad', 'drs_bjd', 'drs_ccf_rv', 'drs_dvrms']
observations = observations[[col for col in cols_to_keep if col in observations.columns]]

cleaned_names = hires_df['main_id_simbad'].str.lower().str.replace(" ", "", regex=False)
harps_stars_set = set(harps_stars)
mask = ~cleaned_names.isin(harps_stars_set)
observations = pd.concat([observations, hires_df[mask]], ignore_index=True)
# observations = observations.dropna(subset=['drs_ccf_rvc'])

observations

       main_id_simbad       drs_bjd    drs_ccf_rv  drs_dvrms  drs_ccf_rvc
0           * tau Cet  2.452902e+06    -16.500015   1.006157          NaN
1           HD 207700  2.452937e+06      6.628923   4.996146          NaN
2           HD 191408  2.452937e+06  99981.724946   0.752430          NaN
3           HD 191408  2.452937e+06  99980.826365   0.708570          NaN
4           HD 191408  2.452937e+06  99981.194811   0.389267          NaN
...               ...           ...           ...        ...          ...
346665         HD1770  2.455404e+06           NaN   0.920000         0.00
346666         HD1770  2.455467e+06           NaN   0.970000         6.29
346667         HD1770  2.455585e+06           NaN   1.150000       -34.73
346668         HD1770  2.456164e+06           NaN   1.110000       -42.43
346669         HD1770  2.458390e+06           NaN   0.860000         1.93

[346670 rows x 5 columns]

In [ ]:
# # Define the column names representing the stars in each dataframe
# harps_star_col = 'star'  # Update to actual column name, e.g., 'OBJECT', 'star', 'name'
# hires_star_col = 'star'  # Update to actual column name

# # Filter out rows from HIRES dataframe where the star is already in the HARPS dataframe
# if harps_star_col in harps_df.columns and hires_star_col in hires_df.columns:
#     harps_stars = harps_df[harps_star_col].unique()
#     hires_filtered = hires_df[~hires_df[hires_star_col].isin(harps_stars)]
# else:
#     # Fallback if the column names are incorrect
#     print(f"Warning: Ensure '{harps_star_col}' and '{hires_star_col}' are the correct column names.")
#     hires_filtered = hires_df

# # Create the new combined dataframe
# combined_df = pd.concat([harps_df, hires_filtered], ignore_index=True)
# combined_df.head()